version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: media_api
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL:  "postgresql://nodejsmediaappdeploy_pg_user:TDnVVZrEIycYC4RMxPeLevYew6l3AjVv@dpg-cqt205lumphs73c5p4d0-a.ohio-postgres.render.com/nodejsmediaappdeploy_pg"
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"

volumes:
  postgres-data: